const DB_SUNDAY = '-sunday';
const DB_MONDAY = '-monday';
const DB_TUESDAY = '-tuesday';
const DB_WEDNESDAY = '-wednesday';
const DB_THURSDAY = '-thursday';
const DB_FRIDAY = '-friday';
const DB_SATURDAY = '-saturday';

const READABLE_SUNDAY = 'Sunday';
const READABLE_MONDAY = 'Monday';
const READABLE_TUESDAY = 'Tuesday';
const READABLE_WEDNESDAY = 'Wednesday';
const READABLE_THURSDAY = 'Thursday';
const READABLE_FRIDAY = 'Friday';
const READABLE_SATURDAY = 'Saturday';

const DB_DAYS_KEYS_TO_READABLE_DAYS = {
  [DB_SUNDAY]: READABLE_SUNDAY,
  [DB_MONDAY]: READABLE_MONDAY,
  [DB_TUESDAY]: READABLE_TUESDAY,
  [DB_WEDNESDAY]: READABLE_WEDNESDAY,
  [DB_THURSDAY]: READABLE_THURSDAY,
  [DB_FRIDAY]: READABLE_FRIDAY,
  [DB_SATURDAY]: READABLE_SATURDAY,
}

const ORDERED_READABLE_DAYS = [
  READABLE_SUNDAY,
  READABLE_MONDAY,
  READABLE_TUESDAY,
  READABLE_WEDNESDAY,
  READABLE_THURSDAY,
  READABLE_FRIDAY,
  READABLE_SATURDAY,
]

export default {
  DB_DAYS_KEYS_TO_READABLE_DAYS: DB_DAYS_KEYS_TO_READABLE_DAYS,
  ORDERED_READABLE_DAYS: ORDERED_READABLE_DAYS,
}